[package]
name = "eth-hound"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
ethers-core = "2.0.14"
ethers-etherscan = "2.0.14"
ethers-providers = "2.0.14"
ethers-signers = "2.0.14"
structopt = "0.3.26"
tokio = { version = "1.39.3", features = ["full"] }
